<a href="https://colab.research.google.com/github/jiyoun1/aipython/blob/main/240109.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

arr = np.arange(10)
print(arr)

arr = np.arange(2, 20, 2)
print(arr)


[0 1 2 3 4 5 6 7 8 9]
[ 2  4  6  8 10 12 14 16 18]


In [3]:
import numpy as np
arr = np.arange(1,10,2)
print(arr)

[1 3 5 7 9]


In [5]:
import numpy as np
arr = np.ones((3,4))
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [6]:
import numpy as np
arr = np.linspace(0,1,10)
print(arr)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [20]:
import numpy as np
A = np.arange(1,26).reshape(5,5)     # A행렬 생성
print(A.shape)                       # A의 모양 출력
print(A[3,3])                        # 19값 출력
print(A[0,0:2],A[1,0:2])             # 슬라이싱으로 [[1,2],[6,7]] 출력
print(A[3,3:5],A[4,3:5])             # 슬라이싱으로 [[19,20],[24,25]] 출력
print(A[0:2,:])                      # 슬라이싱으로 0축(모든 열)의 첫 번째 행과 두 번째 행 추출
print(A[:,3:5])                      # 슬라이싱으로 1축(모든 행)의 마지막 두 열 추출

(5, 5)
19
[1 2] [6 7]
[19 20] [24 25]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 4  5]
 [ 9 10]
 [14 15]
 [19 20]
 [24 25]]


In [26]:
import numpy as np
A = np.arange(1,37).reshape(3,4,3)
print(A.shape)
print(A.size)
print(A)
print(A.flatten())


(3, 4, 3)
36
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]

 [[25 26 27]
  [28 29 30]
  [31 32 33]
  [34 35 36]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]
